### ISSUE TITLE
Добавить поддержку prestashop

### ISSUE THREAD

**Issue by Evil1991** [michaelradionov/bdsm#1]
Конфиг лежит в файле /config/settings.inc.php

define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', '16118');
define('_DB_USER_', 'web');
define('_DB_PASSWD_', 'Bf2UEzyh1w');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_COOKIE_KEY_', 'r6C72W1x7EEPUi3sLI3UnSCTbEC8zT4pTkixHGMoDWxPD36ZYY1HM0SY');
define('_COOKIE_IV_', 'sTpcmJYD');
define('_PS_CREATION_DATE_', '2018-03-06');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.1.18');
define('_RIJNDAEL_KEY_', 'yjzON8aeAK0ZI1VeFi1y79FUaR0e6OG6');
define('_RIJNDAEL_IV_', 'bEW+c9/lqPx/BjvWblcW6g==');

**Comment by michaelradionov** [comment]
Проверяй

**Comment by michaelradionov** [comment]
Проверили. закрываю
